In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [9]:
one_D_array = np.array([1,2,3,4,5])

In [10]:
one_D_array

array([1, 2, 3, 4, 5])

In [18]:
two_D_array = np.array([[1, 2,3], [3, 4, 5]])    

In [20]:
print(one_D_array.shape)
print(two_D_array.shape)

(5,)
(2, 3)


In [24]:
two_D_array.shape

(2, 3)

In [27]:
#array reshaping
print(two_D_array.reshape(3,2))

[[1 2]
 [3 3]
 [4 5]]


In [30]:
#checking dimensions
print(two_D_array.ndim)

2


In [31]:
two_D_array

array([[1, 2, 3],
       [3, 4, 5]])

In [33]:
#Accessing elements array position
print(two_D_array[1,2])

5


In [36]:
#Slicing
print(two_D_array[1:])

[[3 4 5]]


In [37]:
print(two_D_array[:,1:])

[[2 3]
 [4 5]]
